int sub_A7154()
{
  int result; // r0

  sub_D23D4();
  memcpy(&dword_477CB8, &unk_47840C, 0x48u);
  dword_477CB8 = (int)sub_9D8DC;
  dword_477CBC = (int)sub_9BB84;
  dword_477CCC = (int)sub_9D024;
  dword_477CD8 = (int)sub_A8EDC;
  dword_477CDC = (int)sub_9D014;
  dword_477CE4 = (int)sub_9CE70;
  dword_477CE8 = (int)sub_9DB20;
  memcpy(&dword_477D00, &unk_47840C, 0x48u);
  dword_477D00 = (int)sub_9DB6C;
  dword_477D04 = (int)sub_9BB5C;
  dword_477D14 = (int)sub_9D134;
  dword_477D20 = (int)sub_A8ED0;
  dword_477D24 = (int)sub_9D004;
  dword_477D2C = (int)sub_9CE64;
  dword_477D30 = (int)sub_9DB78;
  memcpy(&dword_477D48, &unk_47840C, 0x48u);
  dword_477D48 = (int)sub_9DB70;
  dword_477D4C = (int)sub_9BB34;
  dword_477D5C = (int)sub_9D138;
  dword_477D68 = (int)sub_A8EC4;
  dword_477D6C = (int)sub_9CFF4;
  dword_477D74 = (int)sub_9CE58;
  dword_477D78 = (int)sub_9DBA4;
  memcpy(&dword_477D90, &unk_47840C, 0x48u);
  dword_477D90 = (int)sub_9DB74;
  dword_477D94 = (int)sub_9BB0C;
  dword_477DA4 = (int)sub_9D13C;
  dword_477DB0 = (int)sub_A8EB8;
  dword_477DB4 = (int)sub_9CFE4;
  dword_477DBC = (int)sub_9CE4C;
  dword_477DC0 = (int)sub_9DBD0;
  sub_533F8(
    "ada",
    -1,
    (int)sub_9CC94,
    (int)"Prefix command for changing Ada-specfic settings",
    &dword_477C78,
    (int)"set ada ",
    0,
    (int **)&dword_47475C);
  sub_533F8(
    "ada",
    -1,
    (int)sub_9CC4C,
    (int)"Generic command for showing Ada-specific settings.",
    &dword_477C70,
    (int)"show ada ",
    0,
    (int **)&dword_47474C);
  sub_535B8(
    "trust-PAD-over-XVS",
    10,
    (int)&dword_46BBDC,
    "Enable or disable an optimization trusting PAD types over XVS types",
    "Show whether an optimization trusting PAD types over XVS types is activated",
    "This is related to the encoding used by the GNAT compiler.  The debugger\n"
    "should normally trust the contents of PAD types, but certain older versions\n"
    "of GNAT have a bug that sometimes causes the information in the PAD type\n"
    "to be incorrect.  Turning this setting \"off\" allows the debugger to\n"
    "work around this bug.  It is always safe to turn this option \"off\", but\n"
    "this incurs a slight performance penalty, so it is recommended to NOT change\n"
    "this option to \"off\" unless necessary.",
    0,
    0,
    (int **)&dword_477C78,
    (int **)&dword_477C70);
  sub_535B8(
    "print-signatures",
    1,
    (int)&dword_46BBD8,
    "Enable or disable the output of formal and return types for functions in the overloads selection menu",
    "Show whether the output of formal and return types for functions in the overloads selection menu is activated",
    0,
    0,
    0,
    (int **)&dword_477C78,
    (int **)&dword_477C70);
  sub_D21C4(
    "exception",
    "Catch Ada exceptions, when raised.\nWith an argument, catch only exceptions with the given name.",
    sub_A3B28,
    0,
    0,
    1);
  sub_D21C4(
    "handlers",
    "Catch Ada exceptions, when handled.\nWith an argument, catch only exceptions with the given name.",
    sub_A3A94,
    0,
    0,
    1);
  sub_D21C4(
    "assert",
    "Catch failed Ada assertions, when raised.\nWith an argument, catch only exceptions with the given name.",
    sub_A39A0,
    0,
    0,
    1);
  dword_477C84 = 0x10000;
  sub_5398C(
    "exceptions",
    (int)sub_AF4B8,
    (int)"List all Ada exception names.\n"
         "If a regular expression is passed as an argument, only those matching\n"
         "the regular expression are listed.");
  sub_533F8(
    "ada",
    11,
    (int)sub_9CC64,
    (int)"Set Ada maintenance-related variables.",
    &dword_477C74,
    (int)"maintenance set ada ",
    0,
    (int **)&dword_487A7C);
  sub_533F8(
    "ada",
    11,
    (int)sub_9CC34,
    (int)"Show Ada maintenance-related variables",
    &dword_477C6C,
    (int)"maintenance show ada ",
    0,
    (int **)&dword_487A84);
  sub_535B8(
    "ignore-descriptive-types",
    11,
    (int)&dword_477CAC,
    "Set whether descriptive types generated by GNAT should be ignored.",
    "Show whether descriptive types generated by GNAT should be ignored.",
    "When enabled, the debugger will stop using the DW_AT_GNAT_descriptive_type\nDWARF attribute.",
    0,
    0,
    (int **)&dword_477C74,
    (int **)&dword_477C6C);
  dword_477C9C = sub_323AE0(256, sub_324230, sub_25AA0C, 0, sub_93094, sub_9AD58);
  sub_1B963C(637040);
  sub_1B96F8(645992);
  sub_1BA19C(637080);
  dword_477C68 = sub_183634(0, sub_9B874);
  result = sub_1CD100(0, sub_9B810);
  dword_477C60 = result;
  return result;
}
