int sub_F8744()
{
  sub_259F10("                    GNU GENERAL PUBLIC LICENSE\n");
  sub_259F10("                       Version 3, 29 June 2007\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10(" Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>\n");
  sub_259F10(" Everyone is permitted to copy and distribute verbatim copies\n");
  sub_259F10(" of this license document, but changing it is not allowed.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("                            Preamble\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  The GNU General Public License is a free, copyleft license for\n");
  sub_259F10("software and other kinds of works.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  The licenses for most software and other practical works are designed\n");
  sub_259F10("to take away your freedom to share and change the works.  By contrast,\n");
  sub_259F10("the GNU General Public License is intended to guarantee your freedom to\n");
  sub_259F10("share and change all versions of a program--to make sure it remains free\n");
  sub_259F10("software for all its users.  We, the Free Software Foundation, use the\n");
  sub_259F10("GNU General Public License for most of our software; it applies also to\n");
  sub_259F10("any other work released this way by its authors.  You can apply it to\n");
  sub_259F10("your programs, too.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  When we speak of free software, we are referring to freedom, not\n");
  sub_259F10("price.  Our General Public Licenses are designed to make sure that you\n");
  sub_259F10("have the freedom to distribute copies of free software (and charge for\n");
  sub_259F10("them if you wish), that you receive source code or can get it if you\n");
  sub_259F10("want it, that you can change the software or use pieces of it in new\n");
  sub_259F10("free programs, and that you know you can do these things.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  To protect your rights, we need to prevent others from denying you\n");
  sub_259F10("these rights or asking you to surrender the rights.  Therefore, you have\n");
  sub_259F10("certain responsibilities if you distribute copies of the software, or if\n");
  sub_259F10("you modify it: responsibilities to respect the freedom of others.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  For example, if you distribute copies of such a program, whether\n");
  sub_259F10("gratis or for a fee, you must pass on to the recipients the same\n");
  sub_259F10("freedoms that you received.  You must make sure that they, too, receive\n");
  sub_259F10("or can get the source code.  And you must show them these terms so they\n");
  sub_259F10("know their rights.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Developers that use the GNU GPL protect your rights with two steps:\n");
  sub_259F10("(1) assert copyright on the software, and (2) offer you this License\n");
  sub_259F10("giving you legal permission to copy, distribute and/or modify it.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  For the developers' and authors' protection, the GPL clearly explains\n");
  sub_259F10("that there is no warranty for this free software.  For both users' and\n");
  sub_259F10("authors' sake, the GPL requires that modified versions be marked as\n");
  sub_259F10("changed, so that their problems will not be attributed erroneously to\n");
  sub_259F10("authors of previous versions.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Some devices are designed to deny users access to install or run\n");
  sub_259F10("modified versions of the software inside them, although the manufacturer\n");
  sub_259F10("can do so.  This is fundamentally incompatible with the aim of\n");
  sub_259F10("protecting users' freedom to change the software.  The systematic\n");
  sub_259F10("pattern of such abuse occurs in the area of products for individuals to\n");
  sub_259F10("use, which is precisely where it is most unacceptable.  Therefore, we\n");
  sub_259F10("have designed this version of the GPL to prohibit the practice for those\n");
  sub_259F10("products.  If such problems arise substantially in other domains, we\n");
  sub_259F10("stand ready to extend this provision to those domains in future versions\n");
  sub_259F10("of the GPL, as needed to protect the freedom of users.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Finally, every program is threatened constantly by software patents.\n");
  sub_259F10("States should not allow patents to restrict development and use of\n");
  sub_259F10("software on general-purpose computers, but in those that do, we wish to\n");
  sub_259F10("avoid the special danger that patents applied to a free program could\n");
  sub_259F10("make it effectively proprietary.  To prevent this, the GPL assures that\n");
  sub_259F10("patents cannot be used to render the program non-free.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  The precise terms and conditions for copying, distribution and\n");
  sub_259F10("modification follow.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("                       TERMS AND CONDITIONS\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  0. Definitions.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  \"This License\" refers to version 3 of the GNU General Public License.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  \"Copyright\" also means copyright-like laws that apply to other kinds of\n");
  sub_259F10("works, such as semiconductor masks.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  \"The Program\" refers to any copyrightable work licensed under this\n");
  sub_259F10("License.  Each licensee is addressed as \"you\".  \"Licensees\" and\n");
  sub_259F10("\"recipients\" may be individuals or organizations.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  To \"modify\" a work means to copy from or adapt all or part of the work\n");
  sub_259F10("in a fashion requiring copyright permission, other than the making of an\n");
  sub_259F10("exact copy.  The resulting work is called a \"modified version\" of the\n");
  sub_259F10("earlier work or a work \"based on\" the earlier work.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  A \"covered work\" means either the unmodified Program or a work based\n");
  sub_259F10("on the Program.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  To \"propagate\" a work means to do anything with it that, without\n");
  sub_259F10("permission, would make you directly or secondarily liable for\n");
  sub_259F10("infringement under applicable copyright law, except executing it on a\n");
  sub_259F10("computer or modifying a private copy.  Propagation includes copying,\n");
  sub_259F10("distribution (with or without modification), making available to the\n");
  sub_259F10("public, and in some countries other activities as well.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  To \"convey\" a work means any kind of propagation that enables other\n");
  sub_259F10("parties to make or receive copies.  Mere interaction with a user through\n");
  sub_259F10("a computer network, with no transfer of a copy, is not conveying.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  An interactive user interface displays \"Appropriate Legal Notices\"\n");
  sub_259F10("to the extent that it includes a convenient and prominently visible\n");
  sub_259F10("feature that (1) displays an appropriate copyright notice, and (2)\n");
  sub_259F10("tells the user that there is no warranty for the work (except to the\n");
  sub_259F10("extent that warranties are provided), that licensees may convey the\n");
  sub_259F10("work under this License, and how to view a copy of this License.  If\n");
  sub_259F10("the interface presents a list of user commands or options, such as a\n");
  sub_259F10("menu, a prominent item in the list meets this criterion.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  1. Source Code.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  The \"source code\" for a work means the preferred form of the work\n");
  sub_259F10("for making modifications to it.  \"Object code\" means any non-source\n");
  sub_259F10("form of a work.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  A \"Standard Interface\" means an interface that either is an official\n");
  sub_259F10("standard defined by a recognized standards body, or, in the case of\n");
  sub_259F10("interfaces specified for a particular programming language, one that\n");
  sub_259F10("is widely used among developers working in that language.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  The \"System Libraries\" of an executable work include anything, other\n");
  sub_259F10("than the work as a whole, that (a) is included in the normal form of\n");
  sub_259F10("packaging a Major Component, but which is not part of that Major\n");
  sub_259F10("Component, and (b) serves only to enable use of the work with that\n");
  sub_259F10("Major Component, or to implement a Standard Interface for which an\n");
  sub_259F10("implementation is available to the public in source code form.  A\n");
  sub_259F10("\"Major Component\", in this context, means a major essential component\n");
  sub_259F10("(kernel, window system, and so on) of the specific operating system\n");
  sub_259F10("(if any) on which the executable work runs, or a compiler used to\n");
  sub_259F10("produce the work, or an object code interpreter used to run it.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  The \"Corresponding Source\" for a work in object code form means all\n");
  sub_259F10("the source code needed to generate, install, and (for an executable\n");
  sub_259F10("work) run the object code and to modify the work, including scripts to\n");
  sub_259F10("control those activities.  However, it does not include the work's\n");
  sub_259F10("System Libraries, or general-purpose tools or generally available free\n");
  sub_259F10("programs which are used unmodified in performing those activities but\n");
  sub_259F10("which are not part of the work.  For example, Corresponding Source\n");
  sub_259F10("includes interface definition files associated with source files for\n");
  sub_259F10("the work, and the source code for shared libraries and dynamically\n");
  sub_259F10("linked subprograms that the work is specifically designed to require,\n");
  sub_259F10("such as by intimate data communication or control flow between those\n");
  sub_259F10("subprograms and other parts of the work.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  The Corresponding Source need not include anything that users\n");
  sub_259F10("can regenerate automatically from other parts of the Corresponding\n");
  sub_259F10("Source.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  The Corresponding Source for a work in source code form is that\n");
  sub_259F10("same work.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  2. Basic Permissions.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  All rights granted under this License are granted for the term of\n");
  sub_259F10("copyright on the Program, and are irrevocable provided the stated\n");
  sub_259F10("conditions are met.  This License explicitly affirms your unlimited\n");
  sub_259F10("permission to run the unmodified Program.  The output from running a\n");
  sub_259F10("covered work is covered by this License only if the output, given its\n");
  sub_259F10("content, constitutes a covered work.  This License acknowledges your\n");
  sub_259F10("rights of fair use or other equivalent, as provided by copyright law.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  You may make, run and propagate covered works that you do not\n");
  sub_259F10("convey, without conditions so long as your license otherwise remains\n");
  sub_259F10("in force.  You may convey covered works to others for the sole purpose\n");
  sub_259F10("of having them make modifications exclusively for you, or provide you\n");
  sub_259F10("with facilities for running those works, provided that you comply with\n");
  sub_259F10("the terms of this License in conveying all material for which you do\n");
  sub_259F10("not control copyright.  Those thus making or running the covered works\n");
  sub_259F10("for you must do so exclusively on your behalf, under your direction\n");
  sub_259F10("and control, on terms that prohibit them from making any copies of\n");
  sub_259F10("your copyrighted material outside their relationship with you.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Conveying under any other circumstances is permitted solely under\n");
  sub_259F10("the conditions stated below.  Sublicensing is not allowed; section 10\n");
  sub_259F10("makes it unnecessary.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  3. Protecting Users' Legal Rights From Anti-Circumvention Law.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  No covered work shall be deemed part of an effective technological\n");
  sub_259F10("measure under any applicable law fulfilling obligations under article\n");
  sub_259F10("11 of the WIPO copyright treaty adopted on 20 December 1996, or\n");
  sub_259F10("similar laws prohibiting or restricting circumvention of such\n");
  sub_259F10("measures.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  When you convey a covered work, you waive any legal power to forbid\n");
  sub_259F10("circumvention of technological measures to the extent such circumvention\n");
  sub_259F10("is effected by exercising rights under this License with respect to\n");
  sub_259F10("the covered work, and you disclaim any intention to limit operation or\n");
  sub_259F10("modification of the work as a means of enforcing, against the work's\n");
  sub_259F10("users, your or third parties' legal rights to forbid circumvention of\n");
  sub_259F10("technological measures.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  4. Conveying Verbatim Copies.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  You may convey verbatim copies of the Program's source code as you\n");
  sub_259F10("receive it, in any medium, provided that you conspicuously and\n");
  sub_259F10("appropriately publish on each copy an appropriate copyright notice;\n");
  sub_259F10("keep intact all notices stating that this License and any\n");
  sub_259F10("non-permissive terms added in accord with section 7 apply to the code;\n");
  sub_259F10("keep intact all notices of the absence of any warranty; and give all\n");
  sub_259F10("recipients a copy of this License along with the Program.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  You may charge any price or no price for each copy that you convey,\n");
  sub_259F10("and you may offer support or warranty protection for a fee.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  5. Conveying Modified Source Versions.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  You may convey a work based on the Program, or the modifications to\n");
  sub_259F10("produce it from the Program, in the form of source code under the\n");
  sub_259F10("terms of section 4, provided that you also meet all of these conditions:\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    a) The work must carry prominent notices stating that you modified\n");
  sub_259F10("    it, and giving a relevant date.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    b) The work must carry prominent notices stating that it is\n");
  sub_259F10("    released under this License and any conditions added under section\n");
  sub_259F10("    7.  This requirement modifies the requirement in section 4 to\n");
  sub_259F10("    \"keep intact all notices\".\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    c) You must license the entire work, as a whole, under this\n");
  sub_259F10("    License to anyone who comes into possession of a copy.  This\n");
  sub_259F10("    License will therefore apply, along with any applicable section 7\n");
  sub_259F10("    additional terms, to the whole of the work, and all its parts,\n");
  sub_259F10("    regardless of how they are packaged.  This License gives no\n");
  sub_259F10("    permission to license the work in any other way, but it does not\n");
  sub_259F10("    invalidate such permission if you have separately received it.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    d) If the work has interactive user interfaces, each must display\n");
  sub_259F10("    Appropriate Legal Notices; however, if the Program has interactive\n");
  sub_259F10("    interfaces that do not display Appropriate Legal Notices, your\n");
  sub_259F10("    work need not make them do so.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  A compilation of a covered work with other separate and independent\n");
  sub_259F10("works, which are not by their nature extensions of the covered work,\n");
  sub_259F10("and which are not combined with it such as to form a larger program,\n");
  sub_259F10("in or on a volume of a storage or distribution medium, is called an\n");
  sub_259F10("\"aggregate\" if the compilation and its resulting copyright are not\n");
  sub_259F10("used to limit the access or legal rights of the compilation's users\n");
  sub_259F10("beyond what the individual works permit.  Inclusion of a covered work\n");
  sub_259F10("in an aggregate does not cause this License to apply to the other\n");
  sub_259F10("parts of the aggregate.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  6. Conveying Non-Source Forms.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  You may convey a covered work in object code form under the terms\n");
  sub_259F10("of sections 4 and 5, provided that you also convey the\n");
  sub_259F10("machine-readable Corresponding Source under the terms of this License,\n");
  sub_259F10("in one of these ways:\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    a) Convey the object code in, or embodied in, a physical product\n");
  sub_259F10("    (including a physical distribution medium), accompanied by the\n");
  sub_259F10("    Corresponding Source fixed on a durable physical medium\n");
  sub_259F10("    customarily used for software interchange.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    b) Convey the object code in, or embodied in, a physical product\n");
  sub_259F10("    (including a physical distribution medium), accompanied by a\n");
  sub_259F10("    written offer, valid for at least three years and valid for as\n");
  sub_259F10("    long as you offer spare parts or customer support for that product\n");
  sub_259F10("    model, to give anyone who possesses the object code either (1) a\n");
  sub_259F10("    copy of the Corresponding Source for all the software in the\n");
  sub_259F10("    product that is covered by this License, on a durable physical\n");
  sub_259F10("    medium customarily used for software interchange, for a price no\n");
  sub_259F10("    more than your reasonable cost of physically performing this\n");
  sub_259F10("    conveying of source, or (2) access to copy the\n");
  sub_259F10("    Corresponding Source from a network server at no charge.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    c) Convey individual copies of the object code with a copy of the\n");
  sub_259F10("    written offer to provide the Corresponding Source.  This\n");
  sub_259F10("    alternative is allowed only occasionally and noncommercially, and\n");
  sub_259F10("    only if you received the object code with such an offer, in accord\n");
  sub_259F10("    with subsection 6b.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    d) Convey the object code by offering access from a designated\n");
  sub_259F10("    place (gratis or for a charge), and offer equivalent access to the\n");
  sub_259F10("    Corresponding Source in the same way through the same place at no\n");
  sub_259F10("    further charge.  You need not require recipients to copy the\n");
  sub_259F10("    Corresponding Source along with the object code.  If the place to\n");
  sub_259F10("    copy the object code is a network server, the Corresponding Source\n");
  sub_259F10("    may be on a different server (operated by you or a third party)\n");
  sub_259F10("    that supports equivalent copying facilities, provided you maintain\n");
  sub_259F10("    clear directions next to the object code saying where to find the\n");
  sub_259F10("    Corresponding Source.  Regardless of what server hosts the\n");
  sub_259F10("    Corresponding Source, you remain obligated to ensure that it is\n");
  sub_259F10("    available for as long as needed to satisfy these requirements.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    e) Convey the object code using peer-to-peer transmission, provided\n");
  sub_259F10("    you inform other peers where the object code and Corresponding\n");
  sub_259F10("    Source of the work are being offered to the general public at no\n");
  sub_259F10("    charge under subsection 6d.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  A separable portion of the object code, whose source code is excluded\n");
  sub_259F10("from the Corresponding Source as a System Library, need not be\n");
  sub_259F10("included in conveying the object code work.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  A \"User Product\" is either (1) a \"consumer product\", which means any\n");
  sub_259F10("tangible personal property which is normally used for personal, family,\n");
  sub_259F10("or household purposes, or (2) anything designed or sold for incorporation\n");
  sub_259F10("into a dwelling.  In determining whether a product is a consumer product,\n");
  sub_259F10("doubtful cases shall be resolved in favor of coverage.  For a particular\n");
  sub_259F10("product received by a particular user, \"normally used\" refers to a\n");
  sub_259F10("typical or common use of that class of product, regardless of the status\n");
  sub_259F10("of the particular user or of the way in which the particular user\n");
  sub_259F10("actually uses, or expects or is expected to use, the product.  A product\n");
  sub_259F10("is a consumer product regardless of whether the product has substantial\n");
  sub_259F10("commercial, industrial or non-consumer uses, unless such uses represent\n");
  sub_259F10("the only significant mode of use of the product.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  \"Installation Information\" for a User Product means any methods,\n");
  sub_259F10("procedures, authorization keys, or other information required to install\n");
  sub_259F10("and execute modified versions of a covered work in that User Product from\n");
  sub_259F10("a modified version of its Corresponding Source.  The information must\n");
  sub_259F10("suffice to ensure that the continued functioning of the modified object\n");
  sub_259F10("code is in no case prevented or interfered with solely because\n");
  sub_259F10("modification has been made.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  If you convey an object code work under this section in, or with, or\n");
  sub_259F10("specifically for use in, a User Product, and the conveying occurs as\n");
  sub_259F10("part of a transaction in which the right of possession and use of the\n");
  sub_259F10("User Product is transferred to the recipient in perpetuity or for a\n");
  sub_259F10("fixed term (regardless of how the transaction is characterized), the\n");
  sub_259F10("Corresponding Source conveyed under this section must be accompanied\n");
  sub_259F10("by the Installation Information.  But this requirement does not apply\n");
  sub_259F10("if neither you nor any third party retains the ability to install\n");
  sub_259F10("modified object code on the User Product (for example, the work has\n");
  sub_259F10("been installed in ROM).\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  The requirement to provide Installation Information does not include a\n");
  sub_259F10("requirement to continue to provide support service, warranty, or updates\n");
  sub_259F10("for a work that has been modified or installed by the recipient, or for\n");
  sub_259F10("the User Product in which it has been modified or installed.  Access to a\n");
  sub_259F10("network may be denied when the modification itself materially and\n");
  sub_259F10("adversely affects the operation of the network or violates the rules and\n");
  sub_259F10("protocols for communication across the network.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Corresponding Source conveyed, and Installation Information provided,\n");
  sub_259F10("in accord with this section must be in a format that is publicly\n");
  sub_259F10("documented (and with an implementation available to the public in\n");
  sub_259F10("source code form), and must require no special password or key for\n");
  sub_259F10("unpacking, reading or copying.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  7. Additional Terms.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  \"Additional permissions\" are terms that supplement the terms of this\n");
  sub_259F10("License by making exceptions from one or more of its conditions.\n");
  sub_259F10("Additional permissions that are applicable to the entire Program shall\n");
  sub_259F10("be treated as though they were included in this License, to the extent\n");
  sub_259F10("that they are valid under applicable law.  If additional permissions\n");
  sub_259F10("apply only to part of the Program, that part may be used separately\n");
  sub_259F10("under those permissions, but the entire Program remains governed by\n");
  sub_259F10("this License without regard to the additional permissions.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  When you convey a copy of a covered work, you may at your option\n");
  sub_259F10("remove any additional permissions from that copy, or from any part of\n");
  sub_259F10("it.  (Additional permissions may be written to require their own\n");
  sub_259F10("removal in certain cases when you modify the work.)  You may place\n");
  sub_259F10("additional permissions on material, added by you to a covered work,\n");
  sub_259F10("for which you have or can give appropriate copyright permission.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Notwithstanding any other provision of this License, for material you\n");
  sub_259F10("add to a covered work, you may (if authorized by the copyright holders of\n");
  sub_259F10("that material) supplement the terms of this License with terms:\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    a) Disclaiming warranty or limiting liability differently from the\n");
  sub_259F10("    terms of sections 15 and 16 of this License; or\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    b) Requiring preservation of specified reasonable legal notices or\n");
  sub_259F10("    author attributions in that material or in the Appropriate Legal\n");
  sub_259F10("    Notices displayed by works containing it; or\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    c) Prohibiting misrepresentation of the origin of that material, or\n");
  sub_259F10("    requiring that modified versions of such material be marked in\n");
  sub_259F10("    reasonable ways as different from the original version; or\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    d) Limiting the use for publicity purposes of names of licensors or\n");
  sub_259F10("    authors of the material; or\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    e) Declining to grant rights under trademark law for use of some\n");
  sub_259F10("    trade names, trademarks, or service marks; or\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("    f) Requiring indemnification of licensors and authors of that\n");
  sub_259F10("    material by anyone who conveys the material (or modified versions of\n");
  sub_259F10("    it) with contractual assumptions of liability to the recipient, for\n");
  sub_259F10("    any liability that these contractual assumptions directly impose on\n");
  sub_259F10("    those licensors and authors.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  All other non-permissive additional terms are considered \"further\n");
  sub_259F10("restrictions\" within the meaning of section 10.  If the Program as you\n");
  sub_259F10("received it, or any part of it, contains a notice stating that it is\n");
  sub_259F10("governed by this License along with a term that is a further\n");
  sub_259F10("restriction, you may remove that term.  If a license document contains\n");
  sub_259F10("a further restriction but permits relicensing or conveying under this\n");
  sub_259F10("License, you may add to a covered work material governed by the terms\n");
  sub_259F10("of that license document, provided that the further restriction does\n");
  sub_259F10("not survive such relicensing or conveying.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  If you add terms to a covered work in accord with this section, you\n");
  sub_259F10("must place, in the relevant source files, a statement of the\n");
  sub_259F10("additional terms that apply to those files, or a notice indicating\n");
  sub_259F10("where to find the applicable terms.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Additional terms, permissive or non-permissive, may be stated in the\n");
  sub_259F10("form of a separately written license, or stated as exceptions;\n");
  sub_259F10("the above requirements apply either way.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  8. Termination.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  You may not propagate or modify a covered work except as expressly\n");
  sub_259F10("provided under this License.  Any attempt otherwise to propagate or\n");
  sub_259F10("modify it is void, and will automatically terminate your rights under\n");
  sub_259F10("this License (including any patent licenses granted under the third\n");
  sub_259F10("paragraph of section 11).\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  However, if you cease all violation of this License, then your\n");
  sub_259F10("license from a particular copyright holder is reinstated (a)\n");
  sub_259F10("provisionally, unless and until the copyright holder explicitly and\n");
  sub_259F10("finally terminates your license, and (b) permanently, if the copyright\n");
  sub_259F10("holder fails to notify you of the violation by some reasonable means\n");
  sub_259F10("prior to 60 days after the cessation.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Moreover, your license from a particular copyright holder is\n");
  sub_259F10("reinstated permanently if the copyright holder notifies you of the\n");
  sub_259F10("violation by some reasonable means, this is the first time you have\n");
  sub_259F10("received notice of violation of this License (for any work) from that\n");
  sub_259F10("copyright holder, and you cure the violation prior to 30 days after\n");
  sub_259F10("your receipt of the notice.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Termination of your rights under this section does not terminate the\n");
  sub_259F10("licenses of parties who have received copies or rights from you under\n");
  sub_259F10("this License.  If your rights have been terminated and not permanently\n");
  sub_259F10("reinstated, you do not qualify to receive new licenses for the same\n");
  sub_259F10("material under section 10.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  9. Acceptance Not Required for Having Copies.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  You are not required to accept this License in order to receive or\n");
  sub_259F10("run a copy of the Program.  Ancillary propagation of a covered work\n");
  sub_259F10("occurring solely as a consequence of using peer-to-peer transmission\n");
  sub_259F10("to receive a copy likewise does not require acceptance.  However,\n");
  sub_259F10("nothing other than this License grants you permission to propagate or\n");
  sub_259F10("modify any covered work.  These actions infringe copyright if you do\n");
  sub_259F10("not accept this License.  Therefore, by modifying or propagating a\n");
  sub_259F10("covered work, you indicate your acceptance of this License to do so.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  10. Automatic Licensing of Downstream Recipients.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Each time you convey a covered work, the recipient automatically\n");
  sub_259F10("receives a license from the original licensors, to run, modify and\n");
  sub_259F10("propagate that work, subject to this License.  You are not responsible\n");
  sub_259F10("for enforcing compliance by third parties with this License.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  An \"entity transaction\" is a transaction transferring control of an\n");
  sub_259F10("organization, or substantially all assets of one, or subdividing an\n");
  sub_259F10("organization, or merging organizations.  If propagation of a covered\n");
  sub_259F10("work results from an entity transaction, each party to that\n");
  sub_259F10("transaction who receives a copy of the work also receives whatever\n");
  sub_259F10("licenses to the work the party's predecessor in interest had or could\n");
  sub_259F10("give under the previous paragraph, plus a right to possession of the\n");
  sub_259F10("Corresponding Source of the work from the predecessor in interest, if\n");
  sub_259F10("the predecessor has it or can get it with reasonable efforts.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  You may not impose any further restrictions on the exercise of the\n");
  sub_259F10("rights granted or affirmed under this License.  For example, you may\n");
  sub_259F10("not impose a license fee, royalty, or other charge for exercise of\n");
  sub_259F10("rights granted under this License, and you may not initiate litigation\n");
  sub_259F10("(including a cross-claim or counterclaim in a lawsuit) alleging that\n");
  sub_259F10("any patent claim is infringed by making, using, selling, offering for\n");
  sub_259F10("sale, or importing the Program or any portion of it.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  11. Patents.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  A \"contributor\" is a copyright holder who authorizes use under this\n");
  sub_259F10("License of the Program or a work on which the Program is based.  The\n");
  sub_259F10("work thus licensed is called the contributor's \"contributor version\".\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  A contributor's \"essential patent claims\" are all patent claims\n");
  sub_259F10("owned or controlled by the contributor, whether already acquired or\n");
  sub_259F10("hereafter acquired, that would be infringed by some manner, permitted\n");
  sub_259F10("by this License, of making, using, or selling its contributor version,\n");
  sub_259F10("but do not include claims that would be infringed only as a\n");
  sub_259F10("consequence of further modification of the contributor version.  For\n");
  sub_259F10("purposes of this definition, \"control\" includes the right to grant\n");
  sub_259F10("patent sublicenses in a manner consistent with the requirements of\n");
  sub_259F10("this License.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Each contributor grants you a non-exclusive, worldwide, royalty-free\n");
  sub_259F10("patent license under the contributor's essential patent claims, to\n");
  sub_259F10("make, use, sell, offer for sale, import and otherwise run, modify and\n");
  sub_259F10("propagate the contents of its contributor version.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  In the following three paragraphs, a \"patent license\" is any express\n");
  sub_259F10("agreement or commitment, however denominated, not to enforce a patent\n");
  sub_259F10("(such as an express permission to practice a patent or covenant not to\n");
  sub_259F10("sue for patent infringement).  To \"grant\" such a patent license to a\n");
  sub_259F10("party means to make such an agreement or commitment not to enforce a\n");
  sub_259F10("patent against the party.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  If you convey a covered work, knowingly relying on a patent license,\n");
  sub_259F10("and the Corresponding Source of the work is not available for anyone\n");
  sub_259F10("to copy, free of charge and under the terms of this License, through a\n");
  sub_259F10("publicly available network server or other readily accessible means,\n");
  sub_259F10("then you must either (1) cause the Corresponding Source to be so\n");
  sub_259F10("available, or (2) arrange to deprive yourself of the benefit of the\n");
  sub_259F10("patent license for this particular work, or (3) arrange, in a manner\n");
  sub_259F10("consistent with the requirements of this License, to extend the patent\n");
  sub_259F10("license to downstream recipients.  \"Knowingly relying\" means you have\n");
  sub_259F10("actual knowledge that, but for the patent license, your conveying the\n");
  sub_259F10("covered work in a country, or your recipient's use of the covered work\n");
  sub_259F10("in a country, would infringe one or more identifiable patents in that\n");
  sub_259F10("country that you have reason to believe are valid.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  If, pursuant to or in connection with a single transaction or\n");
  sub_259F10("arrangement, you convey, or propagate by procuring conveyance of, a\n");
  sub_259F10("covered work, and grant a patent license to some of the parties\n");
  sub_259F10("receiving the covered work authorizing them to use, propagate, modify\n");
  sub_259F10("or convey a specific copy of the covered work, then the patent license\n");
  sub_259F10("you grant is automatically extended to all recipients of the covered\n");
  sub_259F10("work and works based on it.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  A patent license is \"discriminatory\" if it does not include within\n");
  sub_259F10("the scope of its coverage, prohibits the exercise of, or is\n");
  sub_259F10("conditioned on the non-exercise of one or more of the rights that are\n");
  sub_259F10("specifically granted under this License.  You may not convey a covered\n");
  sub_259F10("work if you are a party to an arrangement with a third party that is\n");
  sub_259F10("in the business of distributing software, under which you make payment\n");
  sub_259F10("to the third party based on the extent of your activity of conveying\n");
  sub_259F10("the work, and under which the third party grants, to any of the\n");
  sub_259F10("parties who would receive the covered work from you, a discriminatory\n");
  sub_259F10("patent license (a) in connection with copies of the covered work\n");
  sub_259F10("conveyed by you (or copies made from those copies), or (b) primarily\n");
  sub_259F10("for and in connection with specific products or compilations that\n");
  sub_259F10("contain the covered work, unless you entered into that arrangement,\n");
  sub_259F10("or that patent license was granted, prior to 28 March 2007.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Nothing in this License shall be construed as excluding or limiting\n");
  sub_259F10("any implied license or other defenses to infringement that may\n");
  sub_259F10("otherwise be available to you under applicable patent law.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  12. No Surrender of Others' Freedom.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  If conditions are imposed on you (whether by court order, agreement or\n");
  sub_259F10("otherwise) that contradict the conditions of this License, they do not\n");
  sub_259F10("excuse you from the conditions of this License.  If you cannot convey a\n");
  sub_259F10("covered work so as to satisfy simultaneously your obligations under this\n");
  sub_259F10("License and any other pertinent obligations, then as a consequence you may\n");
  sub_259F10("not convey it at all.  For example, if you agree to terms that obligate you\n");
  sub_259F10("to collect a royalty for further conveying from those to whom you convey\n");
  sub_259F10("the Program, the only way you could satisfy both those terms and this\n");
  sub_259F10("License would be to refrain entirely from conveying the Program.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  13. Use with the GNU Affero General Public License.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Notwithstanding any other provision of this License, you have\n");
  sub_259F10("permission to link or combine any covered work with a work licensed\n");
  sub_259F10("under version 3 of the GNU Affero General Public License into a single\n");
  sub_259F10("combined work, and to convey the resulting work.  The terms of this\n");
  sub_259F10("License will continue to apply to the part which is the covered work,\n");
  sub_259F10("but the special requirements of the GNU Affero General Public License,\n");
  sub_259F10("section 13, concerning interaction through a network will apply to the\n");
  sub_259F10("combination as such.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  14. Revised Versions of this License.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  The Free Software Foundation may publish revised and/or new versions of\n");
  sub_259F10("the GNU General Public License from time to time.  Such new versions will\n");
  sub_259F10("be similar in spirit to the present version, but may differ in detail to\n");
  sub_259F10("address new problems or concerns.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Each version is given a distinguishing version number.  If the\n");
  sub_259F10("Program specifies that a certain numbered version of the GNU General\n");
  sub_259F10("Public License \"or any later version\" applies to it, you have the\n");
  sub_259F10("option of following the terms and conditions either of that numbered\n");
  sub_259F10("version or of any later version published by the Free Software\n");
  sub_259F10("Foundation.  If the Program does not specify a version number of the\n");
  sub_259F10("GNU General Public License, you may choose any version ever published\n");
  sub_259F10("by the Free Software Foundation.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  If the Program specifies that a proxy can decide which future\n");
  sub_259F10("versions of the GNU General Public License can be used, that proxy's\n");
  sub_259F10("public statement of acceptance of a version permanently authorizes you\n");
  sub_259F10("to choose that version for the Program.\n");
  sub_259F10((const char *)&word_356638);
  sub_259F10("  Later license versions may give you additional or different\n");
  sub_259F10("permissions.  However, no additional obligations are imposed on any\n");
  sub_259F10("author or copyright holder as a result of your choosing to follow a\n");
  sub_259F10("later version.\n");
  return sub_259F10((const char *)&word_356638);
}
