//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <ctype.h>
#include <errno.h>
#include <netdb.h>
#include <netinet/in.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

// ----------------- Float Types Definitions ------------------

typedef double float64_t;
typedef long double float128_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

struct hostent {
    char *e0;
    char **e1;
    int32_t e2;
    int32_t e3;
    char **e4;
};

struct sockaddr {
    int32_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t function_10614(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10634(char *s1, char *s2);
int32_t function_10640(int32_t fd, int32_t level, int32_t optname,
                       int32_t *optval, int32_t optlen);
int32_t function_1064c(char *format, ...);
int16_t function_10658(int16_t hostshort);
int32_t *function_10664(int32_t *ptr, int32_t size);
int32_t function_10670(char *s);
int32_t *function_1067c(int32_t size);
int32_t function_10688(int32_t main, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)());
char *function_10694(int32_t errnum);
void function_106a0(void);
int16_t **function_106ac(void);
int32_t function_106b8(char *s);
char *function_106c4(char *s, int32_t c);
int32_t function_106d0(struct _IO_FILE *stream, char *format, ...);
int32_t *function_106dc(void);
int32_t *function_106e8(int32_t *s, int32_t c, int32_t n);
int32_t function_106f4(char *nptr);
int32_t function_10700(int32_t domain, int32_t type, int32_t protocol);
struct hostent *function_1070c(char *name);
void function_10718(void);
int32_t function_10724(int32_t fd, int32_t *buf, int32_t n, int32_t flags);
int32_t function_10730(int32_t fd);
int32_t function_1073c(int32_t fd, int32_t *buf, int32_t n, int32_t flags);
int32_t function_10748(int32_t fd, struct sockaddr *addr, int32_t len);
int32_t function_10778(int32_t i_a1);
int32_t function_10784(void);
int32_t function_107a8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10804(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5);
int32_t function_10810(int32_t i_a1);
int32_t function_109f0(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t function_10df0(int32_t i_a1);
int32_t function_10ebc(int32_t i_a1, int32_t i_a2);
int32_t function_11108(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_11144(void);
int32_t function_11148(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t unknown_240(void);

// --------------------- Global Variables ---------------------

char *p_g1;                   // 0x11158
int32_t i_g2 = 0x10811;       // 0x21f10
int32_t i_g3 = 0;             // 0x2206c
struct _IO_FILE *p_g4 = NULL; // 0x22078
int32_t i_g5 = 0;             // 0x22080
int32_t i_g6;

// ------- Dynamically Linked Functions Without Header --------

void __gmon_start__(void);
int32_t __libc_start_main(int32_t i_a1, int32_t i_a2, char **p_a3,
                          void (*p_a4)(), void (*p_a5)(), void (*p_a6)());

// ------------------------ Functions -------------------------

// Address range: 0x10614 - 0x10620
int32_t function_10614(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10614
    return function_10784();
}

// Address range: 0x10634 - 0x10640
int32_t function_10634(char *s1, char *s2) {
    // 0x10634
    return strcmp(s1, s2);
}

// Address range: 0x10640 - 0x1064c
int32_t function_10640(int32_t fd, int32_t level, int32_t optname,
                       int32_t *optval, int32_t optlen) {
    // 0x10640
    return setsockopt(fd, level, optname, optval, optlen);
}

// Address range: 0x1064c - 0x10658
int32_t function_1064c(char *format, ...) {
    // 0x1064c
    return printf(format);
}

// Address range: 0x10658 - 0x10664
int16_t function_10658(int16_t hostshort) {
    // 0x10658
    return htons(hostshort);
}

// Address range: 0x10664 - 0x10670
int32_t *function_10664(int32_t *ptr, int32_t size) {
    // 0x10664
    return realloc(ptr, size);
}

// Address range: 0x10670 - 0x1067c
int32_t function_10670(char *s) {
    // 0x10670
    return puts(s);
}

// Address range: 0x1067c - 0x10688
int32_t *function_1067c(int32_t size) {
    // 0x1067c
    return malloc(size);
}

// Address range: 0x10688 - 0x10694
int32_t function_10688(int32_t main, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x10688
    return __libc_start_main(main, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x10694 - 0x106a0
char *function_10694(int32_t errnum) {
    // 0x10694
    return strerror(errnum);
}

// Address range: 0x106a0 - 0x106ac
void function_106a0(void) {
    // 0x106a0
    __gmon_start__();
}

// Address range: 0x106ac - 0x106b8
int16_t **function_106ac(void) {
    // 0x106ac
    return __ctype_b_loc();
}

// Address range: 0x106b8 - 0x106c4
int32_t function_106b8(char *s) {
    // 0x106b8
    return strlen(s);
}

// Address range: 0x106c4 - 0x106d0
char *function_106c4(char *s, int32_t c) {
    // 0x106c4
    return strchr(s, c);
}

// Address range: 0x106d0 - 0x106dc
int32_t function_106d0(struct _IO_FILE *stream, char *format, ...) {
    // 0x106d0
    return fprintf(stream, format);
}

// Address range: 0x106dc - 0x106e8
int32_t *function_106dc(void) {
    // 0x106dc
    return __errno_location();
}

// Address range: 0x106e8 - 0x106f4
int32_t *function_106e8(int32_t *s, int32_t c, int32_t n) {
    // 0x106e8
    return memset(s, c, n);
}

// Address range: 0x106f4 - 0x10700
int32_t function_106f4(char *nptr) {
    // 0x106f4
    return atoi(nptr);
}

// Address range: 0x10700 - 0x1070c
int32_t function_10700(int32_t domain, int32_t type, int32_t protocol) {
    // 0x10700
    return socket(domain, type, protocol);
}

// Address range: 0x1070c - 0x10718
struct hostent *function_1070c(char *name) {
    // 0x1070c
    return gethostbyname(name);
}

// Address range: 0x10718 - 0x10724
void function_10718(void) {
    // 0x10718
    abort();
}

// Address range: 0x10724 - 0x10730
int32_t function_10724(int32_t fd, int32_t *buf, int32_t n, int32_t flags) {
    // 0x10724
    return recv(fd, buf, n, flags);
}

// Address range: 0x10730 - 0x1073c
int32_t function_10730(int32_t fd) {
    // 0x10730
    return close(fd);
}

// Address range: 0x1073c - 0x10748
int32_t function_1073c(int32_t fd, int32_t *buf, int32_t n, int32_t flags) {
    // 0x1073c
    return send(fd, buf, n, flags);
}

// Address range: 0x10748 - 0x10754
int32_t function_10748(int32_t fd, struct sockaddr *addr, int32_t len) {
    // 0x10748
    return connect(fd, addr, len);
}

// Address range: 0x10754 - 0x10778
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x10754
    int32_t i_v1; // 0x10754
    __libc_start_main(0x10ebc, i_a2, (char **)&i_v1, (void (*)())0x11109,
                      (void (*)())0x10ebc, (void (*)())i_a1);
    abort();
    // UNREACHABLE
}

// Address range: 0x10778 - 0x1077c
int32_t function_10778(int32_t i_a1) {
    // 0x10778
    return i_a1;
}

// Address range: 0x10784 - 0x107a0
int32_t function_10784(void) {
    // 0x10784
    if (i_g3 == 0) {
        int32_t i_v1; // 0x10784
        return i_v1;
    }
    // 0x1079c
    __gmon_start__();
    return &i_g6;
}

// Address range: 0x107a8 - 0x10804
int32_t function_107a8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x107a8
    bool i_v1; // 0x107a8
    if (i_v1) {
        return i_a1;
    }
    // 0x107d8
    int32_t i_v2;                   // 0x107a8
    int32_t i_v3 = 0x100001 * i_v2; // 0x107dc
    bool i_v4;                      // 0x107a8
    int32_t i_v5;                   // 0x107a8
    if (i_v1) {
        // .thread
        i_v5 = i_v1 ? i_v3 : 0;
    } else {
        int32_t i_v6 = i_v3 & -1 - 0x400000 * i_v2; // 0x107e0
        i_v5 = i_v6 < 1 ? 0 : i_v3;
        i_v4 = i_v6 < 0;
        if (i_v6 == 0) {
            return unknown_240();
        }
    }
    // 0x107f0
    if (i_v4 != i_v1) {
        __asm_svclt(0x4770);
    }
    float64_t f_v7; // 0x107a8
    __asm_vqrshl_s8(f_v7, f_v7);
    __asm_vmvn_i32(0xc0000);
    if (!i_v1) {
        *(int32_t *)i_a4 = i_v5;
    }
    return i_a1;
}

// Address range: 0x10804 - 0x10810
int32_t function_10804(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5) {
    int32_t i_v1 = i_a1; // 0x10804
    if (i_a4 == 0) {
        // 0x10806
        i_v1 = function_107a8(i_a1, i_a2, i_a3, 0);
        int32_t i_v2; // 0x10804
        *(char *)i_v2 = 1;
    }
    // 0x1080e
    return i_v1;
}

// Address range: 0x10810 - 0x109f0
int32_t function_10810(int32_t i_a1) {
    if (i_a1 == 0) {
        // 0x109e4
        return __asm_nop();
    }
    char *p_v1 = (char *)i_a1;      // 0x10834
    char *p_v2 = strchr(p_v1, 124); // 0x10834
    char *p_v3 = NULL;              // 0x10844
    if (p_v2 != NULL) {
        // 0x10848
        *p_v2 = 0;
        p_v3 = (char *)((int32_t)p_v2 + 1);
    }
    char *p_v4 = p_v1;   // 0x10868
    char *p_v5;          // 0x10810
    char *p_v6;          // 0x10810
    char *p_v7;          // 0x10810
    char *p_v8;          // 0x10810
    int32_t i_v9;        // 0x10810
    int32_t i_v10;       // 0x10810
    int32_t i_v11;       // 0x109a4
    char *p_v12;         // 0x108d0
    int16_t *p_v13;      // 0x10918
    unsigned char i_v14; // 0x10920
    char *p_v15;         // 0x1088c
    if (!((i_a1 == 0 | *p_v1 == 0))) {
        p_v5 = p_v4;
        i_v9 = 0;
        p_v15 = strchr(p_v5, 44);
        p_v6 = NULL;
        if (p_v15 != NULL) {
            // 0x108a0
            *p_v15 = 0;
            p_v6 = (char *)((int32_t)p_v15 + 1);
        }
        // 0x108b4
        if (*p_v5 != 0) {
            // 0x108c4
            p_v12 = strchr(p_v5, 61);
            p_v7 = NULL;
            if (p_v12 != NULL) {
                // 0x108e4
                *p_v12 = 0;
                p_v7 = (char *)((int32_t)p_v12 + 1);
            }
            // 0x108f8
            p_v8 = p_v7;
            if (i_v9 == 0) {
                // 0x10904
                i_v10 = (int32_t)&p_g1;
                if (p_v8 != NULL) {
                    // 0x10910
                    p_v13 = *__ctype_b_loc();
                    i_v14 = *p_v8;
                    i_v10 = (int32_t)&p_g1;
                    if ((*(int16_t *)(2 * (int32_t)i_v14 + (int32_t)p_v13) &
                         2048) != 0) {
                        // 0x1093c
                        i_v10 = (int32_t)p_v8;
                    }
                }
                // 0x1094c
                printf("[%s%s] =>\n(\n", p_v5, (char *)i_v10);
            }
            if (p_v8 == NULL) {
                // 0x10984
                printf("   [%d] => %s\n", i_v9, p_v5);
            } else {
                // 0x1096c
                printf("   [%s] => %s\n", p_v5, p_v8);
            }
        }
        // 0x10998
        i_v11 = i_v9 + 1;
        while (p_v6 != NULL) {
            // 0x10880
            p_v5 = p_v6;
            i_v9 = i_v11;
            p_v15 = strchr(p_v5, 44);
            p_v6 = NULL;
            if (p_v15 != NULL) {
                // 0x108a0
                *p_v15 = 0;
                p_v6 = (char *)((int32_t)p_v15 + 1);
            }
            // 0x108b4
            if (*p_v5 != 0) {
                // 0x108c4
                p_v12 = strchr(p_v5, 61);
                p_v7 = NULL;
                if (p_v12 != NULL) {
                    // 0x108e4
                    *p_v12 = 0;
                    p_v7 = (char *)((int32_t)p_v12 + 1);
                }
                // 0x108f8
                p_v8 = p_v7;
                if (i_v9 == 0) {
                    // 0x10904
                    i_v10 = (int32_t)&p_g1;
                    if (p_v8 != NULL) {
                        // 0x10910
                        p_v13 = *__ctype_b_loc();
                        i_v14 = *p_v8;
                        i_v10 = (int32_t)&p_g1;
                        if ((*(int16_t *)(2 * (int32_t)i_v14 + (int32_t)p_v13) &
                             2048) != 0) {
                            // 0x1093c
                            i_v10 = (int32_t)p_v8;
                        }
                    }
                    // 0x1094c
                    printf("[%s%s] =>\n(\n", p_v5, (char *)i_v10);
                }
                if (p_v8 == NULL) {
                    // 0x10984
                    printf("   [%d] => %s\n", i_v9, p_v5);
                } else {
                    // 0x1096c
                    printf("   [%s] => %s\n", p_v5, p_v8);
                }
            }
            // 0x10998
            i_v11 = i_v9 + 1;
        }
        if (i_v11 >= 1) {
            // 0x109c4
            puts(")");
        }
    }
    int32_t i_v16 = (int32_t)p_v3; // 0x109e0
    while (p_v3 != NULL) {
        // 0x10828
        p_v1 = (char *)i_v16;
        p_v2 = strchr(p_v1, 124);
        p_v3 = NULL;
        if (p_v2 != NULL) {
            // 0x10848
            *p_v2 = 0;
            p_v3 = (char *)((int32_t)p_v2 + 1);
        }
        // 0x1085c
        p_v4 = p_v1;
        if (!((i_v16 == 0 | *p_v1 == 0))) {
            p_v5 = p_v4;
            i_v9 = 0;
            p_v15 = strchr(p_v5, 44);
            p_v6 = NULL;
            if (p_v15 != NULL) {
                // 0x108a0
                *p_v15 = 0;
                p_v6 = (char *)((int32_t)p_v15 + 1);
            }
            // 0x108b4
            if (*p_v5 != 0) {
                // 0x108c4
                p_v12 = strchr(p_v5, 61);
                p_v7 = NULL;
                if (p_v12 != NULL) {
                    // 0x108e4
                    *p_v12 = 0;
                    p_v7 = (char *)((int32_t)p_v12 + 1);
                }
                // 0x108f8
                p_v8 = p_v7;
                if (i_v9 == 0) {
                    // 0x10904
                    i_v10 = (int32_t)&p_g1;
                    if (p_v8 != NULL) {
                        // 0x10910
                        p_v13 = *__ctype_b_loc();
                        i_v14 = *p_v8;
                        i_v10 = (int32_t)&p_g1;
                        if ((*(int16_t *)(2 * (int32_t)i_v14 + (int32_t)p_v13) &
                             2048) != 0) {
                            // 0x1093c
                            i_v10 = (int32_t)p_v8;
                        }
                    }
                    // 0x1094c
                    printf("[%s%s] =>\n(\n", p_v5, (char *)i_v10);
                }
                if (p_v8 == NULL) {
                    // 0x10984
                    printf("   [%d] => %s\n", i_v9, p_v5);
                } else {
                    // 0x1096c
                    printf("   [%s] => %s\n", p_v5, p_v8);
                }
            }
            // 0x10998
            i_v11 = i_v9 + 1;
            while (p_v6 != NULL) {
                // 0x10880
                p_v5 = p_v6;
                i_v9 = i_v11;
                p_v15 = strchr(p_v5, 44);
                p_v6 = NULL;
                if (p_v15 != NULL) {
                    // 0x108a0
                    *p_v15 = 0;
                    p_v6 = (char *)((int32_t)p_v15 + 1);
                }
                // 0x108b4
                if (*p_v5 != 0) {
                    // 0x108c4
                    p_v12 = strchr(p_v5, 61);
                    p_v7 = NULL;
                    if (p_v12 != NULL) {
                        // 0x108e4
                        *p_v12 = 0;
                        p_v7 = (char *)((int32_t)p_v12 + 1);
                    }
                    // 0x108f8
                    p_v8 = p_v7;
                    if (i_v9 == 0) {
                        // 0x10904
                        i_v10 = (int32_t)&p_g1;
                        if (p_v8 != NULL) {
                            // 0x10910
                            p_v13 = *__ctype_b_loc();
                            i_v14 = *p_v8;
                            i_v10 = (int32_t)&p_g1;
                            if ((*(int16_t *)(2 * (int32_t)i_v14 +
                                              (int32_t)p_v13) &
                                 2048) != 0) {
                                // 0x1093c
                                i_v10 = (int32_t)p_v8;
                            }
                        }
                        // 0x1094c
                        printf("[%s%s] =>\n(\n", p_v5, (char *)i_v10);
                    }
                    if (p_v8 == NULL) {
                        // 0x10984
                        printf("   [%d] => %s\n", i_v9, p_v5);
                    } else {
                        // 0x1096c
                        printf("   [%s] => %s\n", p_v5, p_v8);
                    }
                }
                // 0x10998
                i_v11 = i_v9 + 1;
            }
            if (i_v11 >= 1) {
                // 0x109c4
                puts(")");
            }
        }
        // 0x109d0
        i_v16 = (int32_t)p_v3;
    }
    // 0x109e4
    return __asm_nop();
}

// Address range: 0x109f0 - 0x10df0
int32_t function_109f0(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    char *p_v1 = (char *)i_a2; // 0x10a20
    if (gethostbyname(p_v1) == NULL) {
        // 0x10a34
        printf("Couldn't get hostname: '%s'\n", p_v1);
        // 0x10de4
        return 1;
    }
    int32_t i_v2 = socket(AF_INET, SOCK_STREAM, IPPROTO_IP); // 0x10a58
    if (i_v2 == -1) {
        // 0x10a6c
        printf("Socket initialisation failed: %s\n",
               strerror(*__errno_location()));
        // 0x10de4
        return 1;
    }
    // 0x10a9c
    int32_t i_v3; // bp-52, 0x109f0
    memset(&i_v3, 0, 16);
    i_v3 = 2;
    htons((int16_t)i_a3);
    if (connect(i_v2, (struct sockaddr *)&i_v3, 16) < 0) {
        // 0x10b00
        printf("Socket connect failed: %s\n", strerror(*__errno_location()));
        // 0x10de4
        return 1;
    }
    int32_t i_v4 = 1; // bp-56, 0x10b34
    int32_t i_v5 = 5; // bp-60, 0x10b3c
    int32_t i_v6 = 2; // bp-64, 0x10b44
    setsockopt(i_v2, SO_DEBUG, 9, &i_v4, 4);
    setsockopt(i_v2, SO_BROADCAST, 1, &i_v4, 4);
    setsockopt(i_v2, SO_BROADCAST, 6, &i_v4, 4);
    setsockopt(i_v2, SO_BROADCAST, 4, &i_v5, 4);
    setsockopt(i_v2, SO_BROADCAST, 5, &i_v6, 4);
    int32_t i_v7; // 0x109f0
    if (send(i_v2, (int32_t *)i_a1, strlen((char *)i_a1), 0) < 0) {
        // 0x10c14
        printf("Send failed: %s\n", strerror(*__errno_location()));
        i_v7 = 1;
    lab_0x10dd8:
        // 0x10dd8
        close(i_v2);
        // 0x10de4
        return i_v7;
    }
    int32_t *p_v8 = malloc(0x10000); // 0x10c5c
    if (p_v8 == NULL) {
        // 0x10c74
        printf("Err: OOM (%d)\n", 0x10000);
        // 0x10de4
        return 1;
    }
    char *p_v9 = (char *)p_v8;
    int32_t i_v10 = 0xffff;
    int32_t i_v11 = 0; // 0x109f0
    int32_t i_v12;     // 0x109f0
    int32_t i_v13;     // 0x10cc0
    int32_t i_v14;     // 0x10d08
    while (true) {
        int32_t i_v15 = i_v10;
        char *p_v16 = p_v9;
        char *p_v17 = p_v16;   // 0x10ca8
        int32_t i_v18 = i_v15; // 0x10ca8
        if (i_v15 == i_v11) {
            // 0x10cac
            i_v13 = i_v15 + 0x10000;
            int32_t *p_v19 = realloc((int32_t *)p_v16, i_v13); // 0x10ccc
            p_v17 = (char *)p_v19;
            i_v18 = i_v15 + 0xffff;
            if (p_v19 == NULL) {
                // break -> 0x10ce0
                break;
            }
        }
        // 0x10d00
        i_v10 = i_v18;
        p_v9 = p_v17;
        i_v14 = i_v11 + (int32_t)p_v9;
        int32_t i_v20 =
            recv(i_v2, (int32_t *)i_v14, i_v10 - i_v11, 0); // 0x10d20
        if (i_v20 < 0) {
            // 0x10d34
            printf("Recv failed: %s\n", strerror(*__errno_location()));
            i_v12 = 1;
            goto lab_0x10d8c;
        }
        // 0x10d68
        i_v11 += i_v20;
        if (i_v20 == 0) {
            // 0x10d88
            __asm_nop();
            i_v12 = 0;
            goto lab_0x10d8c;
        }
    }
    // 0x10ce0
    printf("Err: OOM (%d)\n", i_v13);
    // 0x10de4
    return 1;
lab_0x10d8c:
    // 0x10d8c
    *(char *)i_v14 = 0;
    if (i_g5 == 0) {
        // 0x10dc0
        printf("Reply was '%s'\n", p_v9);
        i_v7 = i_v12;
        goto lab_0x10dd8;
    } else {
        // 0x10db4
        puts(p_v9);
        i_v7 = i_v12;
        goto lab_0x10dd8;
    }
}

// Address range: 0x10df0 - 0x10ebc
int32_t function_10df0(int32_t i_a1) {
    uint32_t i_v1 = i_a1;
    int16_t *p_v2 = *__ctype_b_loc(); // 0x10e18
    char *p_v3 = (char *)i_v1;        // 0x10e20
    int32_t i_v4 = i_v1 + 1;          // 0x10e38
    while ((*(int16_t *)(2 * (int32_t)*p_v3 + (int32_t)p_v2) & 0x2000) != 0) {
        // 0x10e10
        i_v1 = i_v4;
        p_v2 = *__ctype_b_loc();
        p_v3 = (char *)i_v1;
        i_v4 = i_v1 + 1;
    }
    int32_t i_v5 = strlen(p_v3) + i_v1; // 0x10e50
    if (i_v1 >= i_v5) {
        // 0x10eac
        return i_v1;
    }
    int32_t i_v6 = i_v5; // 0x10ea8
    i_v6--;
    char *p_v7 = (char *)i_v6;
    int16_t **p_v8 = __ctype_b_loc(); // 0x10e5c
    if ((*(int16_t *)(2 * (int32_t)*p_v7 + (int32_t)*p_v8) & 0x2000) != 0) {
        // 0x10e88
        *p_v7 = 0;
    }
    while (i_v1 < i_v6) {
        // 0x10e5c
        i_v6--;
        p_v7 = (char *)i_v6;
        p_v8 = __ctype_b_loc();
        if ((*(int16_t *)(2 * (int32_t)*p_v7 + (int32_t)*p_v8) & 0x2000) != 0) {
            // 0x10e88
            *p_v7 = 0;
        }
    }
    // 0x10eac
    return i_v1;
}

// Address range: 0x10ebc - 0x11108
int32_t function_10ebc(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = 1; // 0x10f00
    int32_t i_v2;     // 0x10ebc
    if (i_a1 < 2) {
        goto lab_0x10ff4;
    } else {
        int32_t *p_v3 = (int32_t *)(i_a2 + 4);
        i_v2 = (int32_t) "-?";
        if (strcmp((char *)*p_v3, "-?") == 0) {
            goto lab_0x10f7c;
        } else {
            // 0x10f2c
            i_v2 = (int32_t) "-h";
            if (strcmp((char *)*p_v3, "-h") == 0) {
                goto lab_0x10f7c;
            } else {
                // 0x10f54
                i_v2 = (int32_t) "--help";
                if (strcmp((char *)*p_v3, "--help") == 0) {
                    goto lab_0x10f7c;
                } else {
                    // 0x10fb4
                    i_v1 = 1;
                    if (strcmp((char *)*p_v3, "-o") == 0) {
                        // 0x10fdc
                        i_g5 = 1;
                        i_v1 = 2;
                    }
                    goto lab_0x10ff4;
                }
            }
        }
    }
lab_0x10ff4:;
    char *p_v4 = "summary"; // 0x11000
    int32_t i_v5 = i_v1;    // 0x11000
    if (i_v1 < i_a1) {
        char *p_v6 =
            (char *)function_10df0(*(int32_t *)(4 * i_v1 + i_a2)); // 0x11028
        p_v4 = *p_v6 == 0 ? "summary" : p_v6;
        i_v5 = i_v1 + 1;
    }
    char *p_v7 = "127.0.0.1"; // 0x11050
    int32_t i_v8 = i_v5;      // 0x11050
    if (i_v5 < i_a1) {
        char *p_v9 =
            (char *)function_10df0(*(int32_t *)(4 * i_v5 + i_a2)); // 0x11078
        p_v7 = *p_v9 == 0 ? "127.0.0.1" : p_v9;
        i_v8 = i_v5 + 1;
    }
    int32_t i_v10 = 4028; // 0x110a0
    if (i_v8 < i_a1) {
        char *p_v11 =
            (char *)function_10df0(*(int32_t *)(4 * i_v8 + i_a2)); // 0x110c0
        i_v10 = 4028;
        if (*p_v11 != 0) {
            // 0x110d4
            i_v10 = 0x10000 * atoi(p_v11) >> 16;
        }
    }
    // 0x110fc
    return function_109f0((int32_t)p_v4, (int32_t)p_v7, i_v10);
lab_0x10f7c:
    // 0x10f7c
    fprintf(p_g4, "usAge: %s [command [ip/host [port]]]\n", (char *)i_v2);
    // 0x110fc
    return 1;
}

// Address range: 0x11108 - 0x1113c
int32_t function_11108(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_10614(i_a1, i_a2, i_a3, i_a4); // 0x11118
    return 0x21f12 - (int32_t)&i_g2 >> 2 == 0 ? i_v1 : i_a1;
}

// Address range: 0x11144 - 0x11146
int32_t function_11144(void) {
    // 0x11144
    int32_t i_v1; // 0x11144
    return i_v1;
}

// Address range: 0x11148 - 0x11150
int32_t function_11148(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x11148
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 37
